source 'https://rubygems.org'

gem 'json'
gem 'rails'
gem 'railties'
gem 'bcrypt'
gem 'faker'
gem 'carrierwave'
gem 'mini_magick'
gem 'fog'
gem 'CFPropertyList'
gem 'will_paginate'
gem 'bootstrap-will_paginate'
gem 'bootstrap-sass'
gem 'sass-rails'
gem 'uglifier'
gem 'coffee-rails'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder'
gem 'sdoc', group: :doc
gem 'httparty'
gem 'youtube_it'

group :development, :test do
  gem 'pry'
  gem 'sqlite3'    
  gem 'web-console'
  gem 'spring'
  gem 'capistrano',         require: false
  gem 'capistrano-rvm',     require: false
  gem 'capistrano-rails',   require: false
  gem 'capistrano-bundler', require: false
  gem 'capistrano3-puma',   require: false    
end
gem 'puma'

group :test do
  gem 'minitest-reporters'
  gem 'mini_backtrace'
end

group :production do
  gem 'pg'
  gem 'rails_12factor'
end
